# Set the base image for the build stage
FROM amazoncorretto:17.0.7 as build

# Set the working directory
WORKDIR /app

# Copy the Maven wrapper files
COPY mvnw .
COPY mvnw.cmd .

# Copy the project files
COPY pom.xml .

# Copy the source code
COPY src ./src

# Copy the .mvn directory
COPY .mvn .mvn

# Build the application
RUN ./mvnw clean package -DskipTests

# Set the base image for the final stage
FROM amazoncorretto:17.0.7 as runtime

# Set the working directory
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/target/code-challenges-0.0.1-SNAPSHOT.jar app.jar

# Expose the port that the application will run on (adjust as needed)
EXPOSE 8080

# Set the command to run the application
CMD ["java", "-jar", "app.jar"]
